agent:
  name: Cortex-R
  id: cortex_r_001
  description: >
    A reasoning-driven AI agent capable of using external tools
    and memory to solve complex tasks step-by-step.
strategy:
  type: conservative         # Options: conservative, retry_once, explore_all
  max_steps: 3               # Maximum tool-use iterations before termination

memory:
  top_k: 3

llm:
  text_generation: gemini

persona:
  tone: concise
  verbosity: low
  behavior_tags: [rational, focused, tool-using]

mcp_servers:
  - id: PrimeNumberCalculator
    command: python
    script: prime_number_mcp_server.py
    cwd: C:/eag_v1/session4/gmail_assignment
  - id: gmail
    command: C:\eag_v1\session2\agent\Scripts\uv.exe
    script: run,server.py,--creds-file-path,credential.json,--token-path,token.json
    cwd: C:/eag_v1/session4/gmail-mcp-server/src/gmail




# config/profiles.yaml → Agent Profiles / Persona Settings
# Role: Defines agent-specific config: name, strategy, preferences, tool categories.

# Responsibilities:

# Make agent identity configurable without touching code

# Store:

# Name, ID

# Strategy type

# Memory settings

# Tone/personality

# Dependencies:

# context.py and strategy.py load this on startup

# Format: YAML

# Example:

# yaml
# Copy
# Edit
# name: Cortex-R
# strategy: conservative
# memory:
#   top_k: 3
#   type_filter: tool_output
# tone: concise, helpful
# config/profiles.yaml
